### ISSUE TITLE
USER STORY: Sign up

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#12]
**EPIC**: Authentication

As a **user** I can **create a new account** so that **I can access all the features for signed up users**

**Acceptance criteria**

- [ ] Users can create an account
- [ ] Users can access certain features when signed in

**Tasks**

- [ ] Create account function
- [ ] Link to signed in features
