### ISSUE TITLE
USER STORY: Logged in Status

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#14]
**EPIC**: Authentication

As a **user** I can **tell if I am logged in or not** so that **I can log in if I need to** 

**Acceptance criteria**

- [ ] User can make distinction if logged in or not

**Tasks**

- [ ] Create features only accessible when logged in
- [ ] Create icon to indicate user is logged in
