### ISSUE TITLE
USER STORY: Attending event

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#18]
**EPIC**: Attending events

As a **signed in user** I can **indicate I am attending an event** so that **I can support the event and show my interest in it**.

**Acceptance criteria**

- [x] User can indicate they are attending event

**Tasks**

- [x] Create feature that allows user to select if attending event
- [x] Check that user is signed it to allow or prevent feature use
