### ISSUE TITLE
USER STORY: View most recent events

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#19]
**EPIC**: Events page

As a **user** I can **view all the most recent events, ordered by most recently created first** so that **I am up to date with the newest content** 

**Acceptance criteria**

- [ ] User can view most recent events ordered by most recent first

**Tasks**

- [ ] Create view for all events
- [ ] Order by most recent first
