### ISSUE TITLE
USER STORY: Search events

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#20]
**EPIC**: Events page

I can **capability** so that **received benefit**.

As a **user** I can **search for events with keywords,** so that **I can find the events and user profiles I am most interested in.**

**Acceptance criteria**

- [ ] User can search for events with keywords

**Tasks**

- [ ] Create search filter
- [ ] Create categories for searches that can be assigned
