### ISSUE TITLE
USER STORY: Edit event

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#25]
**EPIC**: Event page

As **an event owner** I can **edit event details** so that **I can make corrections or update my event after it was created**

**Acceptance criteria**

- [ ] Event owner can update post

**Tasks**

- [ ] Create view for event user to edit post
- [ ] Validate user is owner of event to allow edit
