### ISSUE TITLE
USER STORY: Create comment

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#26]
**EPIC**: Event page

As a **role** I can **capability** so that **received benefit**.

As a **logged in user** I can **add comments to an event** so that ** I can share my thoughts about the event**

**Acceptance criteria**

- [ ] Logged in user can add comment to event

**Tasks**

- [ ] Create view to allow user to add comment to event
- [ ] Authenticate if user is logged in before adding comment
