### ISSUE TITLE
USER STORY: Delete comment

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#27]
**EPIC**: Event page

As a **role** I can **capability** so that **received benefit**.

As an **owner of a comment** I can **delete my comment** so that **I can control removal of my comment from the application**

**Acceptance criteria**

- [ ] Owner of comment can delete comments

**Tasks**

- [ ] Authenticate user as comment owner
- [ ] Create feaeture that allows user to delete comment
