### ISSUE TITLE
USER STORY: Edit comment

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#28]
**EPIC**: Event page

As a **role** I can **capability** so that **received benefit**.

As an **owner of a comment** I can **edit my comment** so that **I can fix or update my existing comment**

**Acceptance criteria**

- [ ] Comment owner can edit comment

**Tasks**

- [ ] Authenticate that user is comment owner
- [ ] Create feature to allow user to edit comment
