### ISSUE TITLE
USER STORY: Edit profile

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#33]
**EPIC**: Profiles page

As a **logged in user** I can **edit my profile** so that **I can change my profile picture and bio**

**Acceptance criteria**

- [ ] Logged in user can edit profile

**Tasks**

- [ ] Authenticate if user logged in
- [ ] Check if user owner of profile
- [ ] Create feature to allow profile owner to edit profile
