### ISSUE TITLE
USER STORY: Delete event

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#34]
**EPIC**: Event page

As an **event owner** I can **delete an event** so that **control events on the site**.

**Acceptance criteria**

- [ ] An event owner can delete the entry

**Tasks**

- [ ] Authenticate user is event owner
- [ ] Create feature that allows owner to delete event
