### ISSUE TITLE
USER STORY: Create and edit review

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#36]
**EPIC**: Reviews

As a **logged in suer** I can **create, edit, and delete a review of an event** so that **I can leave feedback**.

**Acceptance criteria**

- [ ] Logged in user can leave review of a past event

**Tasks**

- [ ] Authenticate if user logged in
- [ ] Check search field that only shows events in the past
- [ ] Create feature to allow user to add, edit and delete a review

**Comment by MattuW4** [comment]
Whilst the first two tasks have been completed the final one remains outstanding to edit and delete reviews but the critical element has been completed so this task is considered achieved with future features to be implemented.
