### ISSUE TITLE
USER STORY: Front and back end technology

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#38]
**EPIC**: Full stack technologies

As a **site user** I can **interact with the front end that is connected to a back end to store data** so that **I can use the site functionality and have full CRUD over data that I commit and store**.

**Acceptance criteria**

- [ ] Site user can interact with site front end
- [ ] Site user can access and have CRUD over back end

**Tasks**

- [ ] Set up back end repository
- [ ] Build DRF models
- [ ] Set up API
- [ ] Develop Front end with React
- [ ] Connect front and back end via API
- [ ] Run automated and manual testing of site and requisite areas
