### ISSUE TITLE
USER STORY: About us modal

### ISSUE THREAD

**Issue by MattuW4** [MattuW4/out-and-about-frontend#40]
**EPIC**: 

As a **site user** I can **access information about the site if I am a new or returning user** so that **I understand the context of the site and make an immediate connection to it's function**.

**Acceptance criteria**

- [ ] Unregistered site user can access information about the site

**Tasks**

- [ ] Create modal that appears when home page renders for the first time when user is logged out
- [ ] Create links to sign up & sign in page on modal for quick access
- [ ] Create feature to close modal when information has been accessed
- [ ] Create checks to ensure that modal only appears for unregistered users
